import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";
import { ThemeScript } from "./theme-script";
import { NotificationProvider } from "@/contexts/notification-context";
import { FloatingWindowsProvider } from "@/contexts/floating-windows-context";
import { FloatingWindowsRenderer } from "@/components/floating-windows-renderer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <NotificationProvider>
            <FloatingWindowsProvider>
              <ThemeScript />
              {children}
              <FloatingWindowsRenderer />
            </FloatingWindowsProvider>
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
